---
ID: "4673d111-d480-462a-b0fd-b80c2413c1b7"
Parent: "a30447d2-d038-4086-8793-c7086e4d66de"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/main/main-website/Presentation/Headless Variants/CarModelGallery/Default"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260521T000000Z
